config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :imports do
    collection do
      post :import
    end
  end
  get 'imports/index'
  root to: 'imports#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import.rb
class Import < ApplicationRecord
  def self.import(file)
    good_users = []
    bad_users = []
    users = []
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      user = User.new
      user.first_name = row["first_name"].capitalize
      user.last_name = row["last_name"].capitalize
      user.email = row["email"]
      user.error_message = ''
      error = false
      if User.where(email: user.email).count > 0
        error = true
        user.add_error('Email déjà éxistante')
      end
      if User.where(first_name: user.first_name).where(last_name: user.last_name).count > 0
        error = true
        user.add_error('Nom et prénom déjà existants')
      end
      if user.first_name.size < 3
        error = true
        user.add_error('Prénom inférieur à 3 caractères')
      end
      if user.last_name.size < 3
        error = true
        user.add_error('Nom inférieur à 3 caractères')
      end
      if !EmailValidator.valid?(user.email)
        #if user.email =~ /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
        error = true
        user.add_error('Email non conforme')
      end
      if !(/^[[:alpha:]\s'"\-_&@!?()\[\]-]*$/u =~ user.first_name)
        error = true
        user.add_error('Prénom non valide')
      end
      if !(/^[[:alpha:]\s'"\-_&@!?()\[\]-]*$/u =~ user.last_name)
        error = true
        user.add_error('Nom non valide')
      end
      if error
        bad_users.push(user)
      else
        good_users.push(user)
      end
      user.save
    end
    users.push(good_users).push(bad_users)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  def add_error(error)
    if self.error_message != ''
      self.error_message = self.error_message + ', '
    end
    self.error_message = self.error_message + ' ' + error
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def index
  end

  def import
    if params[:file] || File.extname(params[:file]) == '.xlsx'
      @users = Import.import(params[:file])
    else
      redirect_to root_url, notice: 'Pas de fichier fourni.'
    end
  end

  def show
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @good_users = User.where(error_message: '').order(:created_at)
    @bad_users = User.where.not(error_message: '').order(:created_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/imports/import.html.erb
<h1>Utilisateurs importés</h1>
<h3>Sans erreur</h3>
<table class="table table-striped">
  <tr>
    <th>Prénom</th>
    <th>Nom</th>
    <th>Email</th>
  </tr>
  <% @users[0].each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>
<h3>Avec erreur(s)</h3>
<table class="table table-striped">
  <tr>
    <th>Prénom</th>
    <th>Nom</th>
    <th>Email</th>
    <th>Erreur(s)</th>
  </tr>
  <% @users[1].each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.error_message %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Accueil', root_path, class: 'btn btn-primary' %>

app/views/imports/index.html.erb
<h2>Importer les utilsiateurs</h2>
<%= form_tag import_imports_path, multipart: true do %>
  <div class="form-group">
    <label for="input-file">Fichier à importer</label>
    <%= file_field_tag :file, required: true, id: 'input-file', accept: '.xlsx' %>
    <p class="help-block">Utiliser un fichier xlsx</p>
  </div>
  <%= submit_tag 'Importer', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SparkUpTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'SparkUp', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'index', root_path %></li>
            <li><%= link_to 'Utilisateurs', users_index_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Utilisateurs</h1>
<h3>Sans erreur</h3>
<table class="table table-striped">
  <tr>
    <th>Prénom</th>
    <th>Nom</th>
    <th>Email</th>
    <th>Date d'ajout</th>
  </tr>
  <% @good_users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_time.strftime('%m/%d/%Y %H:%M') %></td>
    </tr>
  <% end %>
</table>
<h3>Avec erreur(s)</h3>
<table class="table table-striped">
  <tr>
    <th>Prénom</th>
    <th>Npm</th>
    <th>Email</th>
    <th>Erreur(s)</th>
    <th>Date d'ajout</th>
  </tr>
  <% @bad_users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.error_message %></td>
      <td><%= user.created_at.to_time.strftime('%m/%d/%Y %H:%M') %></td>
    </tr>
  <% end %>
</table>